#!/usr/bin/env python3
"""Recommend top local skills for a user task based on scanned metadata."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, List, Set

EN_TOKEN_RE = re.compile(r"[A-Za-z0-9_\-]+")
ZH_PHRASE_RE = re.compile(r"[\u4e00-\u9fff]{2,}")
STOPWORDS = {"技能", "说明", "使用", "生成", "检查", "帮助", "本地", "一个", "这个", "那个", "可以", "需要"}
DOMAIN_TERMS = {
    "技能导航", "健康度", "健康", "说明书", "缺口", "推荐", "组合", "工作流", "SkillHub", "打包", "安装", "创建",
    "数据分析", "写作", "报告", "调研", "地图", "出行", "知识库", "笔记", "记忆", "专家", "飞书", "企微",
}


def tokenize(text: str) -> Set[str]:
    raw = text or ""
    tokens: Set[str] = {t.lower() for t in EN_TOKEN_RE.findall(raw) if t.strip()}
    for phrase in ZH_PHRASE_RE.findall(raw):
        if phrase not in STOPWORDS:
            tokens.add(phrase)
        for term in DOMAIN_TERMS:
            if term in phrase and term not in STOPWORDS:
                tokens.add(term.lower())
    return {t for t in tokens if t not in STOPWORDS}


def score_skill(task: str, skill: Dict[str, Any]) -> tuple[float, List[str]]:
    task_tokens = tokenize(task)
    fields = {
        "名称": f"{skill.get('english_name','')} {skill.get('chinese_name','')}",
        "说明": skill.get("description_zh", ""),
        "类别": skill.get("category", ""),
    }
    weights = {"名称": 25, "说明": 45, "类别": 15}
    total = 0.0
    relevance_found = False
    reasons: List[str] = []
    for label, value in fields.items():
        tokens = tokenize(str(value))
        if not tokens or not task_tokens:
            continue
        overlap = task_tokens & tokens
        if overlap:
            relevance_found = True
            ratio = min(1.0, len(overlap) / max(2, len(task_tokens)))
            total += weights[label] * ratio
            reasons.append(f"{label}匹配：{', '.join(sorted(list(overlap))[:6])}")
    task_lower = task.lower()
    if any(k.lower() in task_lower for k in ["技能导航", "健康度", "说明书", "缺口", "组合", "skill navigation"]):
        name_and_desc = f"{skill.get('english_name','')} {skill.get('chinese_name','')} {skill.get('description_zh','')}".lower()
        if "navigation" in name_and_desc or "技能导航" in name_and_desc or "技能说明书" in name_and_desc:
            relevance_found = True
            total += 45
            reasons.append("任务属于技能导航/技能库运营场景")
    elif any(k.lower() in task_lower for k in ["skillhub", "打包", "创建", "安装"]):
        category_name = f"{skill.get('category','')} {skill.get('english_name','')} {skill.get('description_zh','')}".lower()
        if "技能创建" in category_name or "skill-creator" in category_name or "skillhub" in category_name:
            relevance_found = True
            total += 18
            reasons.append("任务属于技能创建/SkillHub 场景")
    health = str(skill.get("health") or "").lower()
    if relevance_found:
        if health == "normal":
            total += 10
        elif health == "warning":
            total += 3
    else:
        total = 0
    return round(min(total, 100), 1), reasons or ["与任务存在弱相关，需要人工复核"]


def usage_advice(score: float, rank: int) -> str:
    if rank == 1 and score >= 55:
        return "建议作为主技能单独启动。"
    if score >= 35:
        return "建议作为辅助技能组合使用。"
    return "仅作为备选参考，不建议优先启动。"


def main() -> None:
    parser = argparse.ArgumentParser(description="Match task to top skills")
    parser.add_argument("task", help="User task requirement")
    parser.add_argument("--skills-json", required=True, help="Path to JSON generated by scan_skills.py")
    parser.add_argument("--top", type=int, default=3)
    args = parser.parse_args()
    skills = json.loads(Path(args.skills_json).read_text(encoding="utf-8"))
    ranked = []
    for skill in skills:
        score, reasons = score_skill(args.task, skill)
        ranked.append({**skill, "score": score, "reasons": reasons})
    ranked.sort(key=lambda x: x["score"], reverse=True)
    top = [item for item in ranked if item["score"] > 0][: args.top]
    print(f"任务：{args.task}\n")
    print(f"推荐技能（最多 {args.top} 个）：")
    for i, item in enumerate(top, 1):
        level = "高" if item["score"] >= 60 else "中" if item["score"] >= 35 else "低"
        print(f"{i}. {item['english_name']} / {item['chinese_name']}")
        print(f"   匹配度：{level}（{item['score']}）")
        print(f"   唤起方式：{item['invoke']}")
        print(f"   推荐理由：{'；'.join(item['reasons'])}")
        print(f"   使用建议：{usage_advice(item['score'], i)}")
    if not top:
        print("\n本地没有找到正相关技能，建议进入 SkillHub 搜索补齐流程。")
    elif len(top) < args.top:
        print(f"\n本地只找到 {len(top)} 个正相关技能；如需更多选择，建议进入 SkillHub 搜索补齐流程。")
    elif top[0]["score"] < 35:
        print("\n本地技能匹配度不足，建议进入 SkillHub 搜索补齐流程。")


if __name__ == "__main__":
    main()
